### ISSUE TITLE
does not follow any settings in config files

### ISSUE THREAD

**Issue by alfredodeza** [alfredodeza/khuno.vim#22]
Because the tool will copy the file being linted to a temporary location and it seems flake8 will use the path of the file being linted as the starting place for checking config file settings (vs. the path where flake8 is being executed)

**Comment by alfredodeza** [comment]
@ahills, can you verify this fixes your issue so I can close it and tag a new release? Thanks!

**Comment by ahills** [comment]
It works great! Thanks.
