### ISSUE TITLE
khuno blanks screen requiring screen refresh

### ISSUE THREAD

**Issue by EdwardBetts** [alfredodeza/khuno.vim#23]
When I do ':Kunho run' the screen blanks. I have to hit Ctrl+L for vim to refresh the screen. This is happening when running vim in a terminal window.

Recording available here: https://asciinema.org/a/137883

I'm not sure what's causing this problem.

**Comment by EdwardBetts** [comment]
I recently changed my command shell from bash to fish. This might be related.

**Comment by EdwardBetts** [comment]
I've figured out a minimal test case. The same kind of screen blanking happens when I run

`:execute "! flake8 sample.py"`

**Comment by EdwardBetts** [comment]
Maybe related: https://vi.stackexchange.com/questions/2809/silent-makes-my-vim-go-blank

**Comment by EdwardBetts** [comment]
Related: https://github.com/vim/vim/issues/1253

**Comment by EdwardBetts** [comment]
Maybe Khuno always worked this way, I just never ran ':Kunho run' before.

**Comment by alfredodeza** [comment]
Do you find this acceptable? It might make this flicker *once*:

    diff --git a/ftplugin/python/khuno.vim b/ftplugin/python/khuno.vim
    index 334fda2..5b6a5d3 100644
    --- a/ftplugin/python/khuno.vim
    +++ b/ftplugin/python/khuno.vim
    @@ -458,6 +458,7 @@ function! s:AsyncCmd(cmd)
       let s:khuno_temp_error_file = tempname()
       let command = "! " . a:cmd . " > " . s:khuno_temp_file . " 2> " . s:khuno_temp_error_file . " &"
       silent execute command
    +  redraw!
       let b:khuno_called_async = 1
       let b:khuno_debug.temp_file = s:khuno_temp_file
       let b:khuno_debug.temp_error = s:khuno_temp_error_file

**Comment by EdwardBetts** [comment]
Looks good to me. It is odd that khuno is calling flake8 while I edit the code and the screen doesn't blank, but if I do ':Khuno run' the screen does blank. I'm not sure why the behaviour is different.
Maybe the redraw should be in the Run() function, if that's the only time it is needed.

**Comment by alfredodeza** [comment]
That difference is because one is an autocommand while the other one is a call on command mode. The `redraw!` works perfectly as a workaround, but this needs a bit more tinkering. I might be able to try something else. Thanks for reporting this!

**Comment by alfredodeza** [comment]
I think this is the correct fix, it works better for me. Could you try it out and let me know?

https://github.com/alfredodeza/khuno.vim/commit/12f92b93910693d7f619f1154d3c10089b6c589a

**Comment by alfredodeza** [comment]
Fixed with 12f92b93910693d7f619f1154d3c10089b6c589a and tagged as part of 1.0.3
