### ISSUE TITLE
Problem with f-strings

### ISSUE THREAD

**Issue by axil** [alfredodeza/khuno.vim#25]
```
with open(f'', 'wb') as f:
    pass
```
E999 SyntaxError: invalid syntax

Why?

**Comment by alfredodeza** [comment]
This is not a problem with the plugin, we are just delegating this to flake8. If you run flake8 against that file you will likely see this. The plugin is just relaying the output to the editor.

**Comment by axil** [comment]
flake8 doesn't report an error:

```
% cat zxcv.py
with open(f'', 'wb') as f:
    pass
% flake8 zxcv.py
```

**Comment by alfredodeza** [comment]
Are you using a virtualenv? What system Python version are you using? What Python version is the one in the virtualenv (if any). Where is flake8 installed in the virtualenv or in the system? Are you using a mix of virtualenv packages and system packages?

Again, all that the plugin is doing here is executing flake8 and reporting the errors back. The 'E999 SyntaxError' text is not produced by the plugin, it is coming from flake8

**Comment by axil** [comment]
I've reinstalled both the plugin and flake8 and the problem no longer arises. Thanks.
